'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {

  async up(queryInterface, Sequelize) {

    await queryInterface.bulkInsert(
      "Shoes",
      [
        {
          model: "All Star Converse | Amarillo",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse color amarillas clásicas",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Beige",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 20,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Floreadas",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 10,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Negra",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Roja y blanca",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Rosa",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Turqueza",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Verde",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Violeta claro",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse | Blanca",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "All Star Converse Clasicas | Bota",
          brand: "All Star Converse",
          genre: "unisex",
          description: "All Star Converse",
          stock: 10,
          price: 20200.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans | Beige y blanca",
          brand: "Vans",
          genre: "unisex",
          description: "Vans",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans | Negra",
          brand: "Vans",
          genre: "unisex",
          description: "Vans",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans clásicas | Negra y blanca",
          brand: "Vans",
          genre: "unisex",
          description: "Vans clásicas",
          stock: 10,
          price: 70000.0,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans Clásica | Negra",
          brand: "Vans",
          genre: "unisex",
          description: "Vans Clásica Bota",
          stock: 10,
          price: 70000.0,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans Clásica Bota | Negra",
          brand: "Vans",
          genre: "unisex",
          description: "Vans Clásica Bota",
          stock: 10,
          price: 70000.0,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans | Negra y marrón",
          brand: "Vans",
          genre: "unisex",
          description: "Vans",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans Baja | Negra",
          brand: "Vans",
          genre: "unisex",
          description: "Vans Baja",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans Baja | Roja ",
          brand: "Vans",
          genre: "unisex",
          description: "Vans Baja",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans Bota | Negra",
          brand: "Vans",
          genre: "unisex",
          description: "Vans Bota",
          stock: 10,
          price: 20000.00,
          discount: 0,
          provider:"Ariel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Nike Bicolor | Gris",
          brand: "Nike",
          genre: "unisex",
          description: "Nike Bicolor",
          stock: 10,
          price: 26000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Nike Bicolor | Marrón",
          brand: "Nike",
          genre: "unisex",
          description: "Nike Bicolor",
          stock: 10,
          price: 26000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Nike | Negra",
          brand: "Nike",
          genre: "unisex",
          description: "Nike",
          stock: 10,
          price: 26000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Nike | Negra y Blanca",
          brand: "Nike",
          genre: "unisex",
          description: "Nike",
          stock: 10,
          price: 26000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Nike clásica | Blanca",
          brand: "Nike",
          genre: "unisex",
          description: "Nike clásica",
          stock: 10,
          price: 26000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Nike Bicolor | Verde",
          brand: "Nike",
          genre: "unisex",
          description: "Nike Bicolor",
          stock: 10,
          price: 26000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans | Mostaza",
          brand: "Vans",
          genre: "unisex",
          description: "Vans",
          stock: 10,
          price: 36000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans | Negra",
          brand: "Vans",
          genre: "unisex",
          description: "Vans",
          stock: 10,
          price: 36000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans | Negra y blanco",
          brand: "Vans",
          genre: "unisex",
          description: "Vans",
          stock: 10,
          price: 36000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans clásica | Negra y violeta",
          brand: "Vans",
          genre: "unisex",
          description: "Vans clásica",
          stock: 10,
          price: 36000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans Bicolor | Mostaza y negra",
          brand: "Vans",
          genre: "unisex",
          description: "Vans Bicolor",
          stock: 10,
          price: 36000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Vans Bicolor | Roja y negra",
          brand: "Vans",
          genre: "unisex",
          description: "Vans Bicolor",
          stock: 10,
          price: 36000.00,
          discount: 0,
          provider:"William",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Jordan bajas | Negra y blanca",
          brand: "Nike",
          genre: "unisex",
          description: "Jordan bajas",
          stock: 10,
          price: 70000.0,
          discount: 0,
          provider:"Silvia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Jordan Alta | Negra y blanca",
          brand: "Nike",
          genre: "unisex",
          description: "Jordan Alta",
          stock: 10,
          price: 32000.00,
          discount: 0,
          provider:"Silvia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Air Jordan | Blanca",
          brand: "Nike",
          genre: "unisex",
          description: "Air Jordan",
          stock: 10,
          price: 32000.00,
          discount: 0,
          provider:"Silvia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Jordan | Gris y blanca",
          brand: "Nike",
          genre: "unisex",
          description: "Jordan",
          stock: 10,
          price: 32000.00,
          discount: 0,
          provider:"Silvia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "Jordan | Blanca",
          brand: "Nike",
          genre: "unisex",
          description: "Jordan",
          stock: 10,
          price: 32000.00,
          discount: 0,
          provider:"Silvia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          model: "AirMax | Blanca",
          brand: "Nike",
          genre: "unisex",
          description: "AirMax",
          stock: 10,
          price: 32000.00,
          discount: 0,
          provider:"Silvia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
